### ISSUE TITLE
UASP is missing after flashing JMS579_Z_414.bin

### ISSUE THREAD

**Issue by manelrodero** [Zibri/JMS579#1]
Hi Zibri,

I've tried your customizer with the following options trying to deal with my enclosure errors:

```
[  164.858477] sd 0:0:0:0: [sda] tag#19 uas_eh_abort_handler 0 uas-tag 3 inflight: CMD IN
[  164.858505] sd 0:0:0:0: [sda] tag#19 CDB: opcode=0x28 28 00 00 08 1f 88 00 00 68 00
[  164.858869] sd 0:0:0:0: [sda] tag#10 uas_eh_abort_handler 0 uas-tag 4 inflight: CMD IN
[  164.858882] sd 0:0:0:0: [sda] tag#10 CDB: opcode=0x28 28 00 1b f2 40 00 00 02 00 00
[  164.874499] scsi host0: uas_eh_device_reset_handler start
[  165.003658] usb 2-1: reset SuperSpeed USB device number 2 using xhci_hcd
[  165.029558] scsi host0: uas_eh_device_reset_handler success
```

I've used the following options for generating a `JMS579_Z_414.bin` file:

- Enable USB/SCSI (UASP)
- Enable USB Storage
- Disable 4K block emulation
- Emulate device name/serial
- Disable energy saving

After flashing it to my enclosure it seems errors are gone in `dmesg` output but I've seen some strange things I would like to comment.

* Device ID has changed

**Before**
```
pi@sdpi:~ $ lsusb | grep -i JMicron
Bus 002 Device 002: ID 152d:0578 JMicron Technology Corp. / JMicron USA Technology Corp. JMS578 SATA 6Gb/s
```

**After**
```
pi@sdpi:~/JMicron/JMS578FwUpdater $ lsusb | grep -i JMicron
Bus 002 Device 004: ID 152d:0579 JMicron Technology Corp. / JMicron USA Technology Corp. JMS579
```

* UASP (bInterfaceProtocol 98) is gone :-/

**Before**
```
pi@sdpi:~ $ lsusb -v -d 152d:0578 | grep -i interface
Couldn't open device, some information will be missing
    bNumInterfaces          1
    Interface Descriptor:
      bInterfaceNumber        0
      bInterfaceClass         8 Mass Storage
      bInterfaceSubClass      6 SCSI
      bInterfaceProtocol     80 Bulk-Only
      iInterface              0
    Interface Descriptor:
      bInterfaceNumber        0
      bInterfaceClass         8 Mass Storage
      bInterfaceSubClass      6 SCSI
      bInterfaceProtocol     98
      iInterface              0
```

**After**
```
pi@sdpi:~ $ lsusb -v -d 152d:0579 | grep -i interface
Couldn't open device, some information will be missing
    bNumInterfaces          1
    Interface Descriptor:
      bInterfaceNumber        0
      bInterfaceClass         8 Mass Storage
      bInterfaceSubClass      6 SCSI
      bInterfaceProtocol     80 Bulk-Only
      iInterface              0
```

* Diferences in 'dmesg':
  * bcdDevice changed from 2.04 to 1.14 (???)
  * Correct SSD disk model instead of sobetter EXT (good)
  * USB Storage is used instead of UAS (bad)
  * No disabling FUA message (good?)
  * 4096-byte physical blocks (bad?)
  * New mode sense (???)

**Before**
```
[  133.678212] usb 2-1: new SuperSpeed USB device number 2 using xhci_hcd
[  133.699989] usb 2-1: New USB device found, idVendor=152d, idProduct=0578, bcdDevice= 2.04
[  133.700021] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  133.700037] usb 2-1: Product: JMS579
[  133.700051] usb 2-1: Manufacturer: JMicron
[  133.700064] usb 2-1: SerialNumber: 163260169015
[  133.723720] scsi host0: uas
[  133.728007] scsi 0:0:0:0: Direct-Access     sobetter EXT              0204 PQ: 0 ANSI: 6
[  133.732204] sd 0:0:0:0: [sda] 468862128 512-byte logical blocks: (240 GB/224 GiB)
[  133.732245] sd 0:0:0:0: [sda] 4096-byte physical blocks
[  133.732552] sd 0:0:0:0: [sda] Write Protect is off
[  133.732572] sd 0:0:0:0: [sda] Mode Sense: 53 00 00 08
[  133.733085] sd 0:0:0:0: [sda] Disabling FUA
[  133.733106] sd 0:0:0:0: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[  133.733658] sd 0:0:0:0: [sda] Preferred minimum I/O size 4096 bytes
[  133.733680] sd 0:0:0:0: [sda] Optimal transfer size 33553920 bytes not a multiple of preferred minimum block size (4096 bytes)
[  133.738944]  sda: sda1 sda2
[  133.739854] sd 0:0:0:0: [sda] Attached SCSI disk
[  133.830908] sd 0:0:0:0: Attached scsi generic sg0 type 0
```

**After**

```
[ 3403.279970] usb 2-1: new SuperSpeed USB device number 4 using xhci_hcd
[ 3403.301654] usb 2-1: New USB device found, idVendor=152d, idProduct=0579, bcdDevice= 1.14
[ 3403.301685] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 3403.301703] usb 2-1: Product: JMS579
[ 3403.301717] usb 2-1: Manufacturer: JMICRON
[ 3403.301730] usb 2-1: SerialNumber: 163260169015
[ 3403.309132] usb-storage 2-1:1.0: USB Mass Storage device detected
[ 3403.312494] scsi host0: usb-storage 2-1:1.0
[ 3404.340240] scsi 0:0:0:0: Direct-Access     CT240BX2 00SSD1           0114 PQ: 0 ANSI: 6
[ 3404.340714] sd 0:0:0:0: Attached scsi generic sg0 type 0
[ 3404.340969] sd 0:0:0:0: [sda] 468862128 512-byte logical blocks: (240 GB/224 GiB)
[ 3404.341637] sd 0:0:0:0: [sda] Write Protect is off
[ 3404.341650] sd 0:0:0:0: [sda] Mode Sense: 47 00 00 08
[ 3404.342281] sd 0:0:0:0: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[ 3404.345842]  sda: sda1 sda2
[ 3404.346267] sd 0:0:0:0: [sda] Attached SCSI disk
```

**Why UAS is disabled in your firmware if I've checked the option in your web page?**

Can you explain a little what's going on? I would like to have a working enclosure with optimal performance and no errors but I don't know if this will enough or I'm doing something wrong.

Thanks in advanced for your help.

References:
* Flashing: https://ralimtek.com/posts/2021/jms578/
* UAS: https://superuser.com/questions/928741/how-can-i-check-whether-usb3-0-uasp-usb-attached-scsi-protocol-mode-is-enabled

**Comment by Zibri** [comment]
I don't remember much about this, but if I recall correctly, USB and UASP are mutually exclusive.
Disable USB Storage
Enable USB Storage

or

Enable USB Storage
Disable USB Storage

probably it's the linux driver.
With both enabled on windows it's the O.S. to decide which is better.
And, by the way, UASP in my tests gave no speed advantages (but mine works with HDDs)

**Comment by manelrodero** [comment]
Hi Zibri,

Thanks for this fast response.

I'll try generating a new firmware file after reload your web page. It seems that without a reload, changes in the web interface don't generate a different file. It seems the previous blob is downloaded from GitHub using an URL like this one blob:https://zibri.github.io/c3d1e155-a1c8-42d8-8f8f-6b4ffe6926f5.

Is this the right behaviour?

By the way, I've read the following about UASP. Don't know if we will note something in real world ;-)

https://www.minitool.com/lib/uasp.html
Compared with the traditional USB 3.0 BOT (Bulk-Only Transport), UASP has a 70% increase in read speed at peak performance and a 40% increase in write speed1. Another benefit of UASP is that it reduces the processor resources required by traditional USB when transferring data. At the same peak of the test, UASP shows that it can save up to 80% of processor resources

**Comment by manelrodero** [comment]
Some speed tests.

Using my dual enclosure from Orico (ID 152d:0561 JMicron Technology Corp. / JMicron USA Technology Corp. JMS551 - Sharkoon SATA QuickPort Duo) that has UASP:

```
pi@pi4nas:~ $ sudo dd if=/dev/zero of=/mnt/hdtest oflag=direct bs=128k count=16k
16384+0 records in
16384+0 records out
2147483648 bytes (2.1 GB, 2.0 GiB) copied, 13.4329 s, 160 MB/s
```

Using this new single enclosure  from Posugear (Bus 002 Device 004: ID 152d:0579 JMicron Technology Corp. / JMicron USA Technology Corp. JMS579) with your firmware:

```
pi@sdpi:/mnt/root $ sudo dd if=/dev/zero of=/mnt/hdtest oflag=direct bs=128k count=16k
16384+0 records in
16384+0 records out
2147483648 bytes (2.1 GB, 2.0 GiB) copied, 26.9172 s, 79.8 MB/s
```

I've purchased these enclosures because the dual one doesn't start after a power failure (I need to press a switch button). So it was a none for a Raspberry Pi home server ;-)

I'll continue testing next week and let you know.

Thanks again for your help.

**Comment by Zibri** [comment]
@manelrodero this firmware is intended for HDD enclosures... for SSD I should make another page. And I would need the original firmware to be able to help you.

**Comment by manelrodero** [comment]
Hi @Zibri,

I understand and I appreciate your help.

Here is the link to the original firmware for my POSUGEAR 2.5" Enclosures (https://www.amazon.es/gp/product/B077XVTTJC) extracted using `FwUpdateTool_v1_19_16_24.exe` from Windows:

* https://drive.google.com/file/d/10nQm1Wg0xlWSTAKRPARx_p6PX_S4hnbg/view?usp=sharing

This is the `dmesg` output when connecting the enclosure with a Crucial SSD to my Raspberry Pi:

```
[  363.918488] usb 2-1: new SuperSpeed USB device number 4 using xhci_hcd
[  363.940127] usb 2-1: New USB device found, idVendor=152d, idProduct=0578, bcdDevice= 2.04
[  363.940156] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  363.940172] usb 2-1: Product: JMS579
[  363.940186] usb 2-1: Manufacturer: JMicron
[  363.940199] usb 2-1: SerialNumber: 163260169015
[  363.956152] scsi host0: uas
[  363.957941] scsi 0:0:0:0: Direct-Access     sobetter EXT              0204 PQ: 0 ANSI: 6
[  363.963611] sd 0:0:0:0: [sda] 468862128 512-byte logical blocks: (240 GB/224 GiB)
[  363.963647] sd 0:0:0:0: [sda] 4096-byte physical blocks
[  363.963915] sd 0:0:0:0: [sda] Write Protect is off
[  363.963936] sd 0:0:0:0: [sda] Mode Sense: 53 00 00 08
[  363.964447] sd 0:0:0:0: [sda] Disabling FUA
[  363.964470] sd 0:0:0:0: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[  363.964821] sd 0:0:0:0: Attached scsi generic sg0 type 0
[  363.965038] sd 0:0:0:0: [sda] Preferred minimum I/O size 4096 bytes
[  363.965058] sd 0:0:0:0: [sda] Optimal transfer size 33553920 bytes not a multiple of preferred minimum block size (4096 bytes)
[  363.972580]  sda: sda1 sda2
[  363.973473] sd 0:0:0:0: [sda] Attached SCSI disk
```

And the `lsusb` output is the following:

```
pi@sdpi:~ $ lsusb
Bus 002 Device 004: ID 152d:0578 JMicron Technology Corp. / JMicron USA Technology Corp. JMS578 SATA 6Gb/s
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 0463:ffff MGE UPS Systems UPS
Bus 001 Device 003: ID 10c4:ea60 Silicon Labs CP210x UART Bridge
Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
pi@sdpi:~ $ lsusb -t
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/4p, 5000M
    |__ Port 1: Dev 4, If 0, Class=Mass Storage, Driver=uas, 5000M
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/1p, 480M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/4p, 480M
        |__ Port 3: Dev 3, If 0, Class=Vendor Specific Class, Driver=cp210x, 12M
        |__ Port 4: Dev 4, If 0, Class=Human Interface Device, Driver=usbhid, 1.5M
```

I hope this information is useful for creating a good firmware.

Thanks.

**Comment by manelrodero** [comment]
Hello @Zibri ,

I know that the month of August is usually vacation time, but have you had some free time to review the firmware I shared with you?

Thank you.

**Comment by Zibri** [comment]
hmm.. the modifications I did are in the "nvram" part of the firmware. fwupdatetool afaik does not dump that (but it could.. it depends on the firmware). Anyway, once you have the nvram, open it with a hex editor and check for similarities and differences with similar devices. That's how I found the "flags" for mine.

**Comment by manelrodero** [comment]
Sorry, I don't quite understand what I have to do. You told me that I should give you the original firmware to be able to create a new page that would generate the correct parameters for an SSD.

How should I extract the firmware from the enclosure?

**Comment by Zibri** [comment]
The firmware is made of 2 parts. One is the code and one is the data (settings).
But to extract the firmware from the enclosure is not easy.
Sincerely is long time I am not experimenting with this and I am starting to forget most things.
